/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#1a1c1f",
        "on-surface": "#e2e2e6",
        "on-secondary-container": "#00311f",
        "primary-container": "#00e5ff",
        "surface-container": "#1e2023",
        "tertiary-container": "#fec931",
        "tertiary-fixed-dim": "#f3bf26",
        "tertiary": "#ffeac0",
        "secondary": "#4edea3",
        "primary-fixed": "#9cf0ff",
        "primary-fixed-dim": "#00daf3",
        "on-primary-fixed-variant": "#004f58",
        "tertiary-fixed": "#ffdf96",
        "on-tertiary-fixed-variant": "#594400",
        "error": "#ffb4ab",
        "outline": "#849396",
        "surface-container-lowest": "#0c0e11",
        "surface-container-high": "#282a2d",
        "on-secondary-fixed": "#002113",
        "error-container": "#93000a",
        "surface": "#111316",
        "on-error-container": "#ffdad6",
        "on-tertiary-container": "#6f5500",
        "on-error": "#690005",
        "on-tertiary-fixed": "#251a00",
        "inverse-primary": "#006875",
        "secondary-container": "#00a572",
        "primary": "#c3f5ff",
        "on-secondary-fixed-variant": "#005236",
        "secondary-fixed": "#6ffbbe",
        "on-primary-container": "#00626e",
        "on-surface-variant": "#bac9cc",
        "inverse-surface": "#e2e2e6",
        "on-primary-fixed": "#001f24",
        "surface-dim": "#111316",
        "inverse-on-surface": "#2f3034",
        "on-background": "#e2e2e6",
        "on-primary": "#00363d",
        "surface-tint": "#00daf3",
        "secondary-fixed-dim": "#4edea3",
        "surface-variant": "#333538",
        "on-secondary": "#003824",
        "surface-bright": "#37393d",
        "background": "#111316",
        "surface-container-highest": "#333538",
        "on-tertiary": "#3e2e00",
        "outline-variant": "#3b494c"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Inter"],
        "label": ["Inter"],
        "mono": ["Fira Code"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
